// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzswnqmiorlulstrfico.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6c3ducW1pb3JsdWxzdHJmaWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExODIxMjMsImV4cCI6MjA2Njc1ODEyM30.173rlXJVh3hNxy5KB7hae_FKu_G0jtPtDAkxLR1Lxgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);